- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: izh0407
        password: Sefasboys47 
    
    - name: Build an image and push it to docker hub
      docker_image:
        build:
          path: ./
        name: izh0407/springbootapprepo
        tag: v1
        push: yes
        source: build
