- hosts: localhost
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python3/dist-packages:/home/vagrant/.local/lib/python3.8/site-packages"
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: izh0407
        password: Sefasboys47 
    
    - name: Build an image and push it to docker hub
      docker_image:
        build:
          path: ./
          source: build
        name: izh0407/springbootapprepo
        tag: v1
        push: yes
        
