- hosts: localhost
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: izh0407
        password: Sefasboys47 
    
    - name: Build an image and push it to docker hub
      community.docker.docker_image:
        build:
          path: ./
        name: izh0407/springbootapprepo
        tag: v1
        push: yes
        source: build
